clear;clc;
im=imread('Image.bmp');
subplot(2,2,1);
imshow(im);
title('Image');
%% Histogram
h=histogram(im);
subplot(2,2,2);
plot(h);
title('Image Histogram');
%  %% Histogram Equilization
% im2=histeq(im);
% subplot(2,2,3);
% imshow(im2);
% title('Equilized Histogram');
% 
% h2=imhist(im2);
% subplot(2,2,4);
% plot(h2);

% %% Point Operation
% im3=im*5;
% figure;
% subplot(2,2,1);
% imshow(im3);
% title('Brighten Image');
% 
% %% Median Filtering
% im4=medfilt2(im,[5,5]);
% subplot(2,2,2);
% imshow(im4);
% title('Median Filter');
% im5=im-im4;
% 
% subplot(2,2,3);
% imshow(im5);
% title('High Pass Filter');
% 
% %% Edge Dection
% imE=edge(im);
% subplot(2,2,4);
% imshow(imE);
% title('Edge Image');
% 
% %% Thresholding
% imM=im>40;
% figure;
% subplot(2,2,1);
% imshow(imM);
% title('Mask generated by Thresholding');
% 
% %% Gamma Correction
% imd=double(im);
% [row col]=size(imd);
% %gamma=0.5
% gamma1=0.5;
% out1=abs((1*imd).^gamma1);
% maxm1=max(out1(:));
% minm1=min(out1(:));
% for j=1:row
% 	for k = 1:col
%         out1(j,k)=(255*out1(j,k))/(maxm1-minm1);
% 	end
% end
% out1=uint8(out1);
% 
% %gamma=1.0
% gamma2=1.0;
% out2=abs((1*imd).^gamma2);
% maxm2=max(out2(:));
% minm2=min(out2(:));
% for j=1:row
% 	for k = 1:col
%         out2(j,k)=(255*out2(j,k))/(maxm2-minm2);
% 	end
% end
% out2=uint8(out2);
% 
% %gamma=1.5
% gamma3=1.5;
% out3=abs((1*imd).^gamma3);
% maxm3=max(out3(:));
% minm3=min(out3(:));
% for j=1:row
% 	for k = 1:col
%         out3(j,k)=(255*out3(j,k))/(maxm3-minm3);
% 	end
% end
% out3=uint8(out3);
% 
% subplot(2,2,1);
% imshow(im);
% title('Original Image');
% subplot(2,2,2);
% imshow(out1);
% title('Gamma=0.5');
% subplot(2,2,3);
% imshow(out2);
% title('Gamma=1.0');
% subplot(2,2,4);
% imshow(out3);
% title('Gamma=1.5');